import fs from "fs";
import path from "path";

function slugify(text: string) {
  return text.toString().toLowerCase()
    .replace(/\s+/g, '-')           
    .replace(/[^\w\-]+/g, '')       
    .replace(/\-\-+/g, '-')         
    .replace(/^-+/, '')             
    .replace(/-+$/, '');            
}

const seedPath = path.join(process.cwd(), "prisma", "seed.ts");
const outPath = path.join(process.cwd(), "src", "data", "exercises.ts");

const seedContent = fs.readFileSync(seedPath, "utf-8");

const startMatch = seedContent.indexOf("const EXERCISES_DATA = [");
const endMatch = seedContent.indexOf("];\n\nfunction slugify");

if (startMatch !== -1 && endMatch !== -1) {
  const arrStr = seedContent.substring(startMatch + 23, endMatch + 1);
  const data = eval(arrStr);

  const finalData = data.map((ex: any) => ({
    slug: slugify(ex.name),
    ...ex
  }));

  const outStr = `// This file is auto-generated to serve as the trusted catalog
// Do not edit this file directly.

export const EXERCISES = ${JSON.stringify(finalData, null, 2)};\n`;
  fs.writeFileSync(outPath, outStr, "utf-8");
  console.log("Successfully extracted catalog to src/data/exercises.ts");
} else {
  console.error("Could not find EXERCISES_DATA");
}
